/* THIS FILE IS GENERATED DO NOT EDIT */
#ifndef DONORS_GEN_H
#define DONORS_GEN_H
const char *const DONORS_PATRONS[] = {
	"OSS Capital <https://oss.capital/>",
	"Re-Logic <https://re-logic.com/>",
	0
};
const char *const DONORS_SPONSORS_PLATINUM[] = {
	"Google Play <https://play.google.com/>",
	"Heroic Labs <https://heroiclabs.com/>",
	"Ramatak <https://ramatak.com/>",
	"V-Sekai <https://github.com/V-Sekai>",
	"W4 Games <https://w4games.com/>",
	0
};
const char *const DONORS_SPONSORS_GOLD[] = {
	"Mega Crit <https://www.megacrit.com/>",
	"Pirate Software <https://gopiratesoftware.com/>",
	"Prehensile Tales <https://prehensile-tales.com/>",
	"Robot Gentleman <http://robotgentleman.com/>",
	0
};
const char *const DONORS_SPONSORS_SILVER[] = {
	"Affray Interactive <https://scp.games/pandemic/>",
	"Broken Rules <https://brokenrul.es/>",
	"Chasing Carrots <https://www.chasing-carrots.com/>",
	"Gamblify <https://www.gamblify.com/>",
	"Indoor Astronaut <https://indoorastronaut.ch/>",
	"Null <https://null.com/>",
	"Orbital Knight <https://www.orbitalknight.com/>",
	"Playful Studios <https://playfulstudios.com/>",
	0
};
const char *const DONORS_MEMBERS_DIAMOND[] = {
	"Sealow",
	"Sylv <https://rankith.itch.io/unnamed-space-idle-prototype/>",
	"And 4 anonymous donors",
	0
};
const char *const DONORS_MEMBERS_TITANIUM[] = {
	"Adriaan de Jongh <https://adriaan.games/>",
	"Basically Games",
	"FDG Entertainment <https://www.fdg-entertainment.com/>",
	"Game Dev Artisan <https://gamedevartisan.com/>",
	"Garry Newman",
	"Isaiah Smith <https://www.isaiahsmith.dev/>",
	"Kenney <https://kenney.nl/>",
	"Life Art Studios <https://lifeartstudios.net/>",
	"Lucid Silence Games",
	"Matthew Campbell",
	"Maxim Karsten",
	"PolyMars <https://polymars.dev/>",
	"RPG in a Box <https://www.rpginabox.com/>",
	"Razenpok <https://www.youtube.com/watch?v=-QxI-RP6-HM>",
	"Smirk Software <https://smirk.gg/>",
	"Sterling Long <https://www.sterlinglong.me/>",
	"Sunshower <https://github.com/Phanterm>",
	"TrampolineTales <https://trampolinetales.com/>",
	"\347\262\237\344\272\214\345\215\216 (Su Erhua)",
	"And 4 anonymous donors",
	0
};
const char *const DONORS_MEMBERS_PLATINUM[] = {
	"Andy Touch",
	"BlockImperiumGames (BIG)",
	"Christian Baune",
	"Christoph Woinke",
	"Christopher Shifflett",
	"Darrin Massena",
	"Druvsaft",
	"Edward Flick",
	"getIntoGameDev",
	"HP van Braam",
	"iCommitGames",
	"Jonah Stich",
	"Justin McGettigan",
	"Justo Delgado Baud\303\255",
	"katnamag",
	"Marek Belski",
	"Matthew Ekenstedt",
	"Memories in 8Bit",
	"Mike King",
	"Nassor Paulino da Silva",
	"Neal Gompa (Conan Kudo)",
	"Ronnie Cheng",
	"Ryan Heath",
	"Samantha",
	"Scott Pezza",
	"ShikadiGum",
	"Silver Creek Entertainment",
	"Stephan Kessler",
	"Stephan Lanfermann",
	"TigerJ",
	"Tim Yuen",
	"Violin Iliev",
	"Vladim\303\255r Chv\303\241til",
	"And 16 anonymous donors",
	0
};
const char *const DONORS_MEMBERS_GOLD[] = {
	"@reilaos",
	"alMoo Games",
	"Alva Majo",
	"Antti Vesanen",
	"Artur Ilkaev",
	"Asher Glick",
	"Ben Burbank",
	"Ben Rog-Wilhelm",
	"Benito",
	"Benjamin Sarsgard",
	"Bernd Barsuhn",
	"Blake Farnsworth",
	"Brian Levinsen",
	"Brut",
	"Carlo del Mundo",
	"ClarkThyLord",
	"Cosmin Munteanu",
	"Coy Humphrey",
	"David Chen Zhen",
	"David Coles",
	"David Hubber",
	"David Snopek",
	"Delton Ding",
	"Dustuu",
	"ElektroFox",
	"endaye",
	"Ends",
	"Eric Phy",
	"Faisal Al-Kubaisi (QatariGameDev)",
	"FeralBytes",
	"GlassBrick",
	"Grau",
	"Guangzhou Lingchan",
	"Here's my 20 cents",
	"hiulit",
	"Illyan",
	"Jacob (HACKhalo2 Studios)",
	"Jam",
	"Jason Cawood",
	"Javier Roman",
	"Joel Martinez",
	"John Gabriel",
	"Jon Woodward",
	"Jos\303\251 Canepa",
	"KAR Games",
	"Karasu Studio",
	"korinVR",
	"Kristian Kriehl",
	"Logan Apple",
	"Luca Junge",
	"Luca Vazzano",
	"LyaaaaaGames",
	"MHDante",
	"Malcolm Nixon",
	"Manuel Requena",
	"Mara Huldra",
	"Martin \305\240enke\305\231\303\255k",
	"Megabit Interactive",
	"Modus Ponens",
	"nezticle",
	"Niklas Wahrman",
	"NotNet",
	"Obelisk Island Studios",
	"ohanaya3",
	"Oleksii Nosov",
	"Pav Soor",
	"RAWRLAB Games",
	"RadenTheFolf",
	"Rafa Laguna",
	"Request",
	"re:thinc",
	"Robin Ward",
	"Saltlight Studio",
	"Samuel Judd",
	"Silverclad Studios",
	"Sofox",
	"Space Kraken Studios",
	"Spoony Panda",
	"ThatGamer",
	"ThePolyglotProgrammer",
	"Tim Nedvyga",
	"Tom Langwaldt",
	"Trevor Slocum",
	"tukon",
	"Vincent Foulon",
	"Weasel Games",
	"WuotanStudios.com",
	"Zhu Li",
	"zikes",
	"Alex Khayrullin",
	"Algebrute",
	"Andriy",
	"Antanas Paskauskas",
	"anti666",
	"Ari",
	"Arisaka Mayuki",
	"Arthur S. Muszynski",
	"Bread",
	"Cameron Connolly",
	"Charlie Whitfield",
	"Craig Ostrin",
	"Craig Swain",
	"CzechBlueBear",
	"Daniel Eichler",
	"Dennis Belfrage",
	"Emily A. Bellows",
	"Eric Brand",
	"Felix Winterhalter",
	"Fransiska",
	"Harry Tumber",
	"Harvey Fong",
	"James Couzens",
	"Jared White",
	"Jes\303\272s Chicharro",
	"Joel Fivat",
	"Johnathan Kupferer",
	"Josef Stumpfegger",
	"Josh Nygaard",
	"Joshua Lesperance",
	"Kelteseth",
	"Khora",
	"kickmaniac",
	"Liam Smyth",
	"LoparPanda",
	"Martin Gulliksson",
	"Martin Soucek",
	"Michael D\303\274rwald",
	"Michael Policastro",
	"n00sh",
	"Nicol\303\241s Monner Sans",
	"Nikita Rotskov",
	"Nikola Whallon",
	"Oliver Dick",
	"Patrick Wuttke",
	"Pete Goodwin",
	"Philip Woods",
	"Reilt",
	"Rickard Hermanson",
	"Rob",
	"Rob McInroy",
	"RodZilla",
	"Ruzgud",
	"Ryan Breaker",
	"\042Sage Automatic Systems, LLC\042",
	"spacechase0",
	"sus",
	"Thomas Kurz",
	"Tobias Bocanegra",
	"Torbulous",
	"toto bibi",
	"Valryia",
	"VoidPointer",
	"wpbirney420",
	"Yifan Lai",
	"zkip lan",
	"Aaron Mayfield",
	"Adam Carr",
	"Adam Smeltzer",
	"Adisibio",
	"Adrien de Pierres",
	"Agustinus Arya",
	"Aidan Marwick",
	"Aidan O'Flannagain",
	"aiekick",
	"Aiguo Wang",
	"AJWolbers",
	"Aki Mimoto",
	"Alan Beauchamp",
	"Alejandro Saucedo",
	"Alexander Erlemann",
	"Alex Clavelle",
	"alex raeside",
	"Andre Altmueller",
	"Andreas \303\230stergaard Nielsen",
	"Andrew",
	"Ano Nim",
	"Arch Toasty",
	"Arda Erol",
	"Arturo Rosales",
	"Ash K",
	"Aubrey Falconer",
	"Austin Miller",
	"AzulCrescent",
	"Bal\303\241zs Bat\303\241ri",
	"Beau Seymour",
	"Benedikt",
	"Ben Visness",
	"Bill Thibault",
	"Bread",
	"Brian Ford",
	"Caleb Makela",
	"Cameron Meyer",
	"Carl van der Geest",
	"Cerno_b",
	"ChainZ",
	"Checkpoint Charlie",
	"chendrak",
	"Chris Cavalluzzi",
	"Chris Jagusch",
	"Chris Lee",
	"Christian Mauduit",
	"Christian Ringshofer",
	"Christoph Czurda",
	"Christophe Gagnier",
	"Ciyvius",
	"Cody Parker",
	"Conall O",
	"Corchari",
	"Corey W",
	"cynwav",
	"Dakota Watkins",
	"Daniele Tolomelli",
	"Daniel Ramos",
	"Daren Scot Wilson",
	"Dave Jansen",
	"Davesnothere",
	"David Baker",
	"David B\303\264le",
	"David May",
	"David Maziarka",
	"Devin Carraway",
	"Devin R",
	"Dimitri Roche",
	"Donovan Hutcheon",
	"dragoon",
	"Ducky",
	"Duodecimal",
	"Edward Swartz",
	"Egon Elbre",
	"Elijah Anderson",
	"Eric Persson",
	"Eric Stokes",
	"Eric Williams",
	"Erkki Sepp\303\244l\303\244",
	"Ewan Holmes",
	"Felix Adam",
	"Frank",
	"Frying\342\230\206Pan",
	"Game Endeavor",
	"gamerminstrel",
	"Garrett Steffen",
	"Gary Thomas",
	"gebba",
	"Green Fox",
	"Greyson Richey",
	"Grominet",
	"Guldoman",
	"Guo Hongci",
	"Haplo",
	"Helge Maus",
	"Heribert Hirth",
	"Ian Richard Kunert",
	"Ian Williams",
	"itsybitesyspider",
	"iveks",
	"Jacob Wallace",
	"Jako Danar",
	"James Gary",
	"James Hulsizer",
	"Jamie Massey",
	"JARKKO PARVIAINEN",
	"Jason Evans",
	"Jeff Hungerford",
	"Jeffrey Berube",
	"Jennifer Graves",
	"Joakim Askenb\303\244ck",
	"Jonas",
	"Jonas Arndt",
	"Jonas Yamazaki",
	"Jonathan Bieber",
	"Jon Sully",
	"Joseph Catrambone",
	"Josh Taylor",
	"Joshua Heidrich",
	"Juanfran",
	"Juan Maggi",
	"Julian le Roux",
	"Justin Spedding",
	"Kalydi Bal\303\241zs",
	"Keegan Scott",
	"Keith Bradner",
	"Kent Jofur",
	"kindzadza",
	"Kodera Software",
	"KsyTek Games",
	"Kyle Burnett",
	"Kyle Haltermann",
	"Kyle Jacobs",
	"Leland Vakarian",
	"Levi Berciu",
	"liberodark",
	"Linus Lind Lundgren",
	"Ludovic DELVAL",
	"Luigi Renna",
	"Luis Morao",
	"Lukas Komischke",
	"Luke Diasio",
	"Major Haul",
	"Malcolm",
	"Manuele Finocchiaro",
	"Marcos Heitor Carvalho",
	"Markie Music",
	"Mark Tyler",
	"Markus Michael Egger",
	"Martin Holas",
	"Martin Li\305\241ka",
	"Martin Trbola",
	"Mat\304\233j Dr\303\241bek",
	"Mateo Navarrete",
	"Mathieu",
	"Matt Edwards",
	"Maverick",
	"Maxime Blade",
	"Maxwell",
	"Melissa Mears",
	"Metal Demon 2000",
	"Michael Morrison",
	"Michal Skwarek",
	"Mikael Nordenberg",
	"Mikayla",
	"Mike Copley",
	"Molly Jameson",
	"MoltenGears",
	"Moritz Weissenberger",
	"MrAZIE",
	"Mrjemandem",
	"naonya3",
	"Nathaniel",
	"neighty",
	"Neil Blakey-Milner",
	"Neofytos Chimonas",
	"Nerdforge",
	"Nerdyninja",
	"Nick Eldrenkamp",
	"Nicolas Rosset",
	"Nik Rudenko",
	"Noel Billig",
	"Oscar Domingo",
	"ozrk",
	"Parth Patel",
	"Patrick Horn",
	"Patrickm",
	"Patrick Nafarrete",
	"Paul Black",
	"Paul Gieske",
	"Paul Mozet",
	"Pete",
	"Philip Ludington (MrPhil)",
	"Phoenix Jauregui",
	"Pierre Caye",
	"Pixel Archipel",
	"Point08",
	"Portponky",
	"PsycHead",
	"Quincy Quincy",
	"Quinn Morrison",
	"Raghava Kovvali",
	"RagingRoosevelt",
	"Ragnar Pettersson",
	"Rammeow",
	"Rebecca H",
	"Richard Hayes",
	"Riley",
	"RobotCritter",
	"Roka",
	"Roland Rz\304\205sa",
	"Russ",
	"Ryan Groom",
	"Sammy Fischer",
	"Satnam Singh",
	"Sebastian Michailidis",
	"SeongWan Kim",
	"Sessamekesh",
	"Shane Lillie",
	"Shane Spoor",
	"Shaun Kohanowski",
	"simdee",
	"Simon Jonas Larsen",
	"Simon Schoenenberger",
	"Sina Yeganeh",
	"sirn",
	"Skalli",
	"slavfox",
	"smbe19",
	"smo1704",
	"SpicyCactuar",
	"SquidgySapphic",
	"Squirrel",
	"Stephen Rice",
	"Stephen Schlie",
	"Sven Walter",
	"SxP",
	"tadashi endo",
	"Tarch",
	"TheVoiceInMyHead",
	"Thibaut DECROMBECQUE",
	"thomas",
	"Thomas Bechtold",
	"Thomas Pickett",
	"Tim Drumheller",
	"Tim Klein",
	"Timothy B. MacDonald",
	"Tim Raveling",
	"Tim Riley",
	"Tom Webster",
	"Trent Skinner",
	"Tyler Stafos",
	"Tyler Stepke",
	"Uther",
	"Vaughan Ling",
	"vgmoose",
	"vlnx",
	"Wapiti .",
	"Wiley Thompson",
	"Xatonym",
	"Zekim",
	"\343\202\261\343\203\253\343\203\231\343\203\255\343\202\271",
	"\350\262\264\345\256\217 \345\260\217\346\235\276",
	"And 208 anonymous donors",
	0
};
#endif // DONORS_GEN_H
